# Generated by Django 3.1.5 on 2021-01-21 14:33
from __future__ import unicode_literals
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='/media/default.png', upload_to=''),
        ),
    ]
